<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="platformer" nsURI="http://www.example.org/platformer" nsPrefix="platformer">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Game">
    <eOperations name="startGame"/>
    <eOperations name="resetGame"/>
    <eOperations name="endGame"/>
    <eOperations name="loadLevel"/>
    <eOperations name="update"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="currentLevelCounter" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="levels" lowerBound="1"
        upperBound="-1" eType="#//Level" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ui" lowerBound="1" eType="#//UI"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="friction" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gravity" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lives" lowerBound="1" eType="#//Lives"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="screen" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="clock" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="running" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="score" lowerBound="1" eType="#//Score"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Level">
    <eOperations name="update"/>
    <eOperations name="draw"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="#//Status"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entities" upperBound="-1"
        eType="#//Entity" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="background" lowerBound="1"
        eType="#//Image" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="winCoordinate" lowerBound="1"
        eType="#//Array2D" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Status">
    <eLiterals name="INCOMPLETE"/>
    <eLiterals name="COMPLETE" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ItemType">
    <eLiterals name="SCORE"/>
    <eLiterals name="ABILITY" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PlatformType">
    <eLiterals name="STILL" value="1"/>
    <eLiterals name="MOVING" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EnemyType">
    <eLiterals name="PASSIVE"/>
    <eLiterals name="ACTIVE" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UI">
    <eOperations name="draw"/>
    <eOperations name="handle_click"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="button" lowerBound="4"
        upperBound="4" eType="#//Button" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="livesCount" lowerBound="1"
        eType="#//Lives"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scoreCount" lowerBound="1"
        eType="#//Score"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="menu_open" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Button">
    <eOperations name="performAction"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="action" eType="#//ButtonType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ButtonType">
    <eLiterals name="RESET_GAME"/>
    <eLiterals name="EXIT_GAME" value="1"/>
    <eLiterals name="OPEN_MENU" value="2"/>
    <eLiterals name="CLOSE_MENU" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entity" abstract="true">
    <eOperations name="updatePosition"/>
    <eOperations name="draw"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" eType="#//Direction"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="speed" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="position" lowerBound="1"
        eType="#//Array2D" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sprite" lowerBound="1"
        upperBound="-1" eType="#//Image" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Player" eSuperTypes="#//Entity">
    <eOperations name="jump"/>
    <eOperations name="performAction"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="powered_up" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="powered_time" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="jump_speed" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="on_ground" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Enemy" eSuperTypes="#//Entity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//EnemyType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Platform" eSuperTypes="#//Entity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//PlatformType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Item" eSuperTypes="#//Entity">
    <eOperations name="applyEffect"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//ItemType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Direction">
    <eLiterals name="LEFT"/>
    <eLiterals name="RIGHT" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Image">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Array2D">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Lives">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="amount" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Score">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="amount" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Pygame" instanceTypeName="Pygame"/>
</ecore:EPackage>
